use std::time::SystemTime;

use log::{debug, warn};
use regex::Regex;
use serde::{Deserialize, Serialize};

/// Severity of a behavioral alert.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum AlertSeverity {
    Low,
    Medium,
    High,
    Critical,
}

/// Simple MITRE ATT&CK reference.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MitreTechnique {
    pub id: String,   // e.g. "T1059.001"
    pub name: String, // e.g. "PowerShell"
}

/// Behavioral alert generated by the analyzer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BehavioralAlert {
    pub severity: AlertSeverity,
    pub title: String,
    pub description: String,
    pub mitre_techniques: Vec<MitreTechnique>,
    pub process_image: String,
    pub process_command_line: String,
    pub parent_image: Option<String>,
    pub pid: u32,
    pub ppid: u32,
    pub timestamp: SystemTime,
}

/// Minimal view of a process event the analyzer needs.
///
/// Implement this on your actual process-event struct so you don't
/// have to change the analyzer when your telemetry schema changes.
pub trait ProcessEventView {
    fn pid(&self) -> u32;
    fn ppid(&self) -> u32;
    fn image_path(&self) -> &str;
    fn command_line(&self) -> &str;
    fn timestamp(&self) -> SystemTime;
    fn parent_image_path(&self) -> Option<&str>; // if you have it; otherwise None
}

/// Database of LOLBin abuse patterns.
struct LolBinPattern {
    binary: &'static str,
    arg_regex: Regex,
    description: &'static str,
    mitre: MitreTechnique,
}

struct LolBinDatabase {
    patterns: Vec<LolBinPattern>,
}

impl LolBinDatabase {
    fn new() -> Self {
        let mut patterns = Vec::new();

        // certutil.exe download & decode
        patterns.push(LolBinPattern {
            binary: "certutil.exe",
            arg_regex: Regex::new(r"(?i)-urlcache.*http").unwrap(),
            description: "certutil used to download file from the web",
            mitre: MitreTechnique {
                id: "T1105".to_string(), // Ingress Tool Transfer
                name: "Ingress Tool Transfer".to_string(),
            },
        });
        patterns.push(LolBinPattern {
            binary: "certutil.exe",
            arg_regex: Regex::new(r"(?i)-decode").unwrap(),
            description: "certutil used to decode base64 or encoded file",
            mitre: MitreTechnique {
                id: "T1140".to_string(), // Deobfuscate/Decode Files or Information
                name: "Deobfuscate/Decode Files or Information".to_string(),
            },
        });

        // mshta.exe remote HTA
        patterns.push(LolBinPattern {
            binary: "mshta.exe",
            arg_regex: Regex::new(r"(?i)http").unwrap(),
            description: "mshta executing remote HTA script",
            mitre: MitreTechnique {
                id: "T1218.005".to_string(), // Mshta
                name: "Mshta".to_string(),
            },
        });

        // rundll32.exe executing script / suspicious command
        patterns.push(LolBinPattern {
            binary: "rundll32.exe",
            arg_regex: Regex::new(r"(?i)(javascript:|vbscript:)").unwrap(),
            description: "rundll32 executing script content",
            mitre: MitreTechnique {
                id: "T1218.011".to_string(), // Rundll32
                name: "Rundll32".to_string(),
            },
        });

        // regsvr32.exe executing remote scriptlet
        patterns.push(LolBinPattern {
            binary: "regsvr32.exe",
            arg_regex: Regex::new(r"(?i)/s.*http").unwrap(),
            description: "regsvr32 loading remote scriptlet/DLL",
            mitre: MitreTechnique {
                id: "T1218.010".to_string(), // Regsvr32
                name: "Regsvr32".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "wmic.exe",
            arg_regex: Regex::new(r"(?i)(process\s+call\s+create|/format:.*\.xsl|http)").unwrap(),
            description: "wmic used for process execution or XSL script abuse",
            mitre: MitreTechnique {
                id: "T1047".to_string(),
                name: "Windows Management Instrumentation".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "bitsadmin.exe",
            arg_regex: Regex::new(r"(?i)(/transfer|/addfile|https?://)").unwrap(),
            description: "bitsadmin used for payload transfer",
            mitre: MitreTechnique {
                id: "T1197".to_string(),
                name: "BITS Jobs".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "msiexec.exe",
            arg_regex: Regex::new(r"(?i)(/i\s+https?://|/qn\b|/quiet\b)").unwrap(),
            description: "msiexec used for remote MSI execution",
            mitre: MitreTechnique {
                id: "T1218.007".to_string(),
                name: "Msiexec".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "cmstp.exe",
            arg_regex: Regex::new(r"(?i)(\.inf\b|/s\b)").unwrap(),
            description: "cmstp used with INF installation bypass",
            mitre: MitreTechnique {
                id: "T1218.003".to_string(),
                name: "CMSTP".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "forfiles.exe",
            arg_regex: Regex::new(r"(?i)(/c\s+|cmd\s+/c|powershell)").unwrap(),
            description: "forfiles used for indirect command execution",
            mitre: MitreTechnique {
                id: "T1202".to_string(),
                name: "Indirect Command Execution".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "pcalua.exe",
            arg_regex: Regex::new(r"(?i)(-a\s+|/a\s+|https?://)").unwrap(),
            description: "pcalua used as proxy execution binary",
            mitre: MitreTechnique {
                id: "T1202".to_string(),
                name: "Indirect Command Execution".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "wscript.exe",
            arg_regex: Regex::new(r"(?i)(\.js\b|\.vbs\b|https?://|//e:|//b)").unwrap(),
            description: "wscript used for scripted payload execution",
            mitre: MitreTechnique {
                id: "T1059.005".to_string(),
                name: "Visual Basic".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "cscript.exe",
            arg_regex: Regex::new(r"(?i)(\.js\b|\.vbs\b|https?://|//e:|//nologo)").unwrap(),
            description: "cscript used for scripted payload execution",
            mitre: MitreTechnique {
                id: "T1059.007".to_string(),
                name: "JavaScript".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "msdt.exe",
            arg_regex: Regex::new(r"(?i)(ms-msdt:|/id\s+pcwdiagnostic|it_browseforfile)").unwrap(),
            description: "msdt invocation consistent with Follina-style abuse",
            mitre: MitreTechnique {
                id: "T1218".to_string(),
                name: "Signed Binary Proxy Execution".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "installutil.exe",
            arg_regex: Regex::new(r"(?i)(/u\b|/logfile=|https?://|\.dll\b|\.exe\b)").unwrap(),
            description: "InstallUtil used for .NET proxy execution",
            mitre: MitreTechnique {
                id: "T1218.004".to_string(),
                name: "InstallUtil".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "msbuild.exe",
            arg_regex: Regex::new(r"(?i)(\.xml\b|https?://|/nologo|/target:)").unwrap(),
            description: "MSBuild used for inline task or project-based execution",
            mitre: MitreTechnique {
                id: "T1127.001".to_string(),
                name: "MSBuild".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "regasm.exe",
            arg_regex: Regex::new(r"(?i)(/u\b|/codebase\b|\.dll\b)").unwrap(),
            description: "RegAsm used as signed proxy execution binary",
            mitre: MitreTechnique {
                id: "T1218".to_string(),
                name: "Signed Binary Proxy Execution".to_string(),
            },
        });

        patterns.push(LolBinPattern {
            binary: "powershell.exe",
            arg_regex: Regex::new(r"(?i)(\[ref\]\.assembly|amsiinitfailed|set-mppreference|add-mppreference|-ep\s+bypass)").unwrap(),
            description: "PowerShell command-line indicates AMSI/policy bypass behavior",
            mitre: MitreTechnique {
                id: "T1059.001".to_string(),
                name: "PowerShell".to_string(),
            },
        });

        Self { patterns }
    }

    fn analyze(&self, image_path: &str, command_line: &str) -> Vec<BehavioralAlert> {
        let mut alerts = Vec::new();
        let exe_name = image_path
            .rsplit(['\\', '/'])
            .next()
            .unwrap_or(image_path)
            .to_lowercase();

        for pattern in &self.patterns {
            if exe_name == pattern.binary {
                if pattern.arg_regex.is_match(command_line) {
                    let alert = BehavioralAlert {
                        severity: AlertSeverity::High,
                        title: "LOLBin Abuse Detected".to_string(),
                        description: format!("{}: {}", exe_name, pattern.description),
                        mitre_techniques: vec![pattern.mitre.clone()],
                        process_image: image_path.to_string(),
                        process_command_line: command_line.to_string(),
                        parent_image: None,
                        pid: 0,
                        ppid: 0,
                        timestamp: SystemTime::now(),
                    };
                    alerts.push(alert);
                }
            }
        }

        alerts
    }
}

/// Behavioral analyzer entry point.
pub struct BehavioralAnalyzer {
    lolbins: LolBinDatabase,
}

impl BehavioralAnalyzer {
    pub fn new() -> Self {
        Self {
            lolbins: LolBinDatabase::new(),
        }
    }

    /// Main analysis entry point for process creation events.
    ///
    /// Returns zero or more alerts for this process start.
    pub fn analyze_process_start<E: ProcessEventView>(&self, ev: &E) -> Vec<BehavioralAlert> {
        let mut alerts = Vec::new();

        // Heuristic buckets:
        // 1) Suspicious parent-child chains
        self.check_office_spawns_scripts(ev, &mut alerts);
        self.check_services_spawns_unusual(ev, &mut alerts);

        // 2) Command-line obfuscation / download cradles
        self.check_commandline_obfuscation(ev, &mut alerts);
        self.check_download_cradles(ev, &mut alerts);

        // 3) LOLBin abuse
        self.check_lolbin_abuse(ev, &mut alerts);

        if !alerts.is_empty() {
            debug!(
                "BehavioralAnalyzer produced {} alert(s) for PID {}",
                alerts.len(),
                ev.pid()
            );
        }

        alerts
    }

    fn check_office_spawns_scripts<E: ProcessEventView>(
        &self,
        ev: &E,
        out: &mut Vec<BehavioralAlert>,
    ) {
        let parent_image = ev.parent_image_path().unwrap_or_default().to_lowercase();
        let image = ev.image_path().to_lowercase();

        let is_office_parent = ["winword.exe", "excel.exe", "powerpnt.exe", "outlook.exe"]
            .iter()
            .any(|p| parent_image.ends_with(p));

        let is_script_child = [
            "powershell.exe",
            "pwsh.exe",
            "cmd.exe",
            "wscript.exe",
            "cscript.exe",
            "mshta.exe",
        ]
        .iter()
        .any(|c| image.ends_with(c));

        if is_office_parent && is_script_child {
            warn!(
                "Office->Script chain: {} → {} (PID {}, PPID {})",
                parent_image,
                image,
                ev.pid(),
                ev.ppid()
            );

            out.push(BehavioralAlert {
                severity: AlertSeverity::High,
                title: "Office Application Spawned Script Interpreter".to_string(),
                description: format!(
                    "Parent {} spawned {}, which is commonly used in macro-based attacks",
                    parent_image, image
                ),
                mitre_techniques: vec![
                    MitreTechnique {
                        id: "T1204.002".to_string(), // Malicious File
                        name: "Malicious File".to_string(),
                    },
                    MitreTechnique {
                        id: "T1059.001".to_string(), // PowerShell
                        name: "PowerShell".to_string(),
                    },
                ],
                process_image: ev.image_path().to_string(),
                process_command_line: ev.command_line().to_string(),
                parent_image: Some(ev.parent_image_path().unwrap_or("").to_string()),
                pid: ev.pid(),
                ppid: ev.ppid(),
                timestamp: ev.timestamp(),
            });
        }
    }

    fn check_services_spawns_unusual<E: ProcessEventView>(
        &self,
        ev: &E,
        out: &mut Vec<BehavioralAlert>,
    ) {
        let parent_image = ev.parent_image_path().unwrap_or_default().to_lowercase();
        let image = ev.image_path().to_lowercase();

        if !parent_image.ends_with("services.exe") {
            return;
        }

        // Allowlist some common children of services.exe; everything else is suspicious.
        let allowed_children_suffixes = [
            "svchost.exe",
            "lsass.exe",
            "winlogon.exe",
            "spoolsv.exe",
            "smss.exe",
        ];

        let is_allowed = allowed_children_suffixes.iter().any(|p| image.ends_with(p));

        if !is_allowed {
            warn!(
                "services.exe spawned unusual process {} (PID {}, PPID {})",
                image,
                ev.pid(),
                ev.ppid()
            );

            out.push(BehavioralAlert {
                severity: AlertSeverity::Critical,
                title: "Services.exe Spawned Unusual Child Process".to_string(),
                description: format!(
                    "services.exe spawned {}, which is not in the known-safe list",
                    image
                ),
                mitre_techniques: vec![MitreTechnique {
                    id: "T1543.003".to_string(), // Windows Service
                    name: "Windows Service".to_string(),
                }],
                process_image: ev.image_path().to_string(),
                process_command_line: ev.command_line().to_string(),
                parent_image: Some(ev.parent_image_path().unwrap_or("").to_string()),
                pid: ev.pid(),
                ppid: ev.ppid(),
                timestamp: ev.timestamp(),
            });
        }
    }

    fn check_commandline_obfuscation<E: ProcessEventView>(
        &self,
        ev: &E,
        out: &mut Vec<BehavioralAlert>,
    ) {
        let cmd = ev.command_line();

        // PowerShell encodedcommand
        let lower = cmd.to_lowercase();
        if lower.contains("-encodedcommand") || lower.contains(" -enc ") {
            out.push(BehavioralAlert {
                severity: AlertSeverity::Medium,
                title: "PowerShell Encoded Command".to_string(),
                description:
                    "PowerShell invoked with -EncodedCommand/-enc, likely obfuscated payload."
                        .to_string(),
                mitre_techniques: vec![MitreTechnique {
                    id: "T1027".to_string(), // Obfuscated Files or Information
                    name: "Obfuscated Files or Information".to_string(),
                }],
                process_image: ev.image_path().to_string(),
                process_command_line: ev.command_line().to_string(),
                parent_image: ev.parent_image_path().map(|s| s.to_string()),
                pid: ev.pid(),
                ppid: ev.ppid(),
                timestamp: ev.timestamp(),
            });
        }

        // Excessive obfuscation characters: ^, `, + in CMD/PS
        let obf_chars = ['^', '`', '+'];
        let obf_count: usize = obf_chars.iter().map(|c| cmd.matches(*c).count()).sum();

        if obf_count > 10 {
            out.push(BehavioralAlert {
                severity: AlertSeverity::High,
                title: "Command-Line Obfuscation Detected".to_string(),
                description: format!(
                    "Command-line contains {} obfuscation characters (^,`,+), likely evasion.",
                    obf_count
                ),
                mitre_techniques: vec![MitreTechnique {
                    id: "T1027".to_string(),
                    name: "Obfuscated Files or Information".to_string(),
                }],
                process_image: ev.image_path().to_string(),
                process_command_line: ev.command_line().to_string(),
                parent_image: ev.parent_image_path().map(|s| s.to_string()),
                pid: ev.pid(),
                ppid: ev.ppid(),
                timestamp: ev.timestamp(),
            });
        }
    }

    fn check_download_cradles<E: ProcessEventView>(&self, ev: &E, out: &mut Vec<BehavioralAlert>) {
        let cmd = ev.command_line().to_lowercase();

        // Common PowerShell/BITS download indicators
        let indicators = [
            "downloadstring",
            "downloadfile",
            "invoke-webrequest",
            "invoke-restmethod",
            "bitsadmin",
            "start-bitstransfer",
            "curl ",
            "wget ",
            "http://",
            "https://",
        ];

        if indicators.iter().any(|p| cmd.contains(p)) {
            out.push(BehavioralAlert {
                severity: AlertSeverity::High,
                title: "Potential Download Cradle Detected".to_string(),
                description:
                    "Process command-line contains web download or transfer primitives; may be staging payloads."
                        .to_string(),
                mitre_techniques: vec![MitreTechnique {
                    id: "T1105".to_string(), // Ingress Tool Transfer
                    name: "Ingress Tool Transfer".to_string(),
                }],
                process_image: ev.image_path().to_string(),
                process_command_line: ev.command_line().to_string(),
                parent_image: ev.parent_image_path().map(|s| s.to_string()),
                pid: ev.pid(),
                ppid: ev.ppid(),
                timestamp: ev.timestamp(),
            });
        }
    }

    fn check_lolbin_abuse<E: ProcessEventView>(&self, ev: &E, out: &mut Vec<BehavioralAlert>) {
        let mut alerts = self.lolbins.analyze(ev.image_path(), ev.command_line());

        // Fill PID/PPID/timestamps in the generated alerts
        for a in &mut alerts {
            a.pid = ev.pid();
            a.ppid = ev.ppid();
            a.parent_image = ev.parent_image_path().map(|s| s.to_string());
            a.timestamp = ev.timestamp();
        }

        out.extend(alerts);
    }
}
