use std::time::SystemTime;

use serde::{Deserialize, Serialize};

/// Severity for memory/injection alerts.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum MemoryAlertSeverity {
    Low,
    Medium,
    High,
    Critical,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MitreTechnique {
    pub id: String,   // e.g. "T1055"
    pub name: String, // e.g. "Process Injection"
}

/// High-level memory/injection alert generated by analyzer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryAlert {
    pub severity: MemoryAlertSeverity,
    pub title: String,
    pub description: String,
    pub mitre_techniques: Vec<MitreTechnique>,

    pub source_pid: u32,
    pub source_image: String,
    pub target_pid: Option<u32>,
    pub target_image: Option<String>,

    pub address: Option<u64>,
    pub size: Option<u64>,
    pub old_protection: Option<u32>,
    pub new_protection: Option<u32>,

    pub timestamp: SystemTime,
}

/// View of a remote-thread / APC injection event.
pub trait InjectionEventView {
    fn source_pid(&self) -> u32;
    fn source_image(&self) -> &str;
    fn target_pid(&self) -> u32;
    fn target_image(&self) -> &str;
    fn timestamp(&self) -> SystemTime;
    fn technique_hint(&self) -> InjectionTechniqueHint; // from driver
}

/// View of a memory-protection-change event.
pub trait MemProtEventView {
    fn pid(&self) -> u32;
    fn process_image(&self) -> &str;
    fn address(&self) -> u64;
    fn size(&self) -> u64;
    fn old_protection(&self) -> u32;
    fn new_protection(&self) -> u32;
    fn timestamp(&self) -> SystemTime;
}

/// View of an LSASS access event.
pub trait LsassAccessEventView {
    fn source_pid(&self) -> u32;
    fn source_image(&self) -> &str;
    fn access_mask(&self) -> u32;
    fn timestamp(&self) -> SystemTime;
}

/// Hint from kernel about the suspected injection technique.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InjectionTechniqueHint {
    CreateRemoteThread,
    QueueUserApc,
    ProcessHollowing,
    Unknown,
}

pub struct MemoryAnalyzer;

impl MemoryAnalyzer {
    pub fn new() -> Self {
        Self
    }

    /// Analyze an injection-style event (remote thread / APC / hollowing).
    pub fn analyze_injection<E: InjectionEventView>(&self, ev: &E) -> MemoryAlert {
        let (title, desc, severity, mitre) = match ev.technique_hint() {
            InjectionTechniqueHint::CreateRemoteThread => (
                "CreateRemoteThread Injection Detected".to_string(),
                format!(
                    "Process {} (PID {}) created a remote thread in {} (PID {}).",
                    ev.source_image(),
                    ev.source_pid(),
                    ev.target_image(),
                    ev.target_pid()
                ),
                MemoryAlertSeverity::Critical,
                MitreTechnique {
                    id: "T1055".to_string(),
                    name: "Process Injection".to_string(),
                },
            ),
            InjectionTechniqueHint::QueueUserApc => (
                "APC-Based Injection Detected".to_string(),
                format!(
                    "Process {} (PID {}) queued an APC into {} (PID {}).",
                    ev.source_image(),
                    ev.source_pid(),
                    ev.target_image(),
                    ev.target_pid()
                ),
                MemoryAlertSeverity::High,
                MitreTechnique {
                    id: "T1055".to_string(),
                    name: "Process Injection".to_string(),
                },
            ),
            InjectionTechniqueHint::ProcessHollowing => (
                "Process Hollowing Detected".to_string(),
                format!(
                    "Process {} (PID {}) appears to be hollowing {} (PID {}).",
                    ev.source_image(),
                    ev.source_pid(),
                    ev.target_image(),
                    ev.target_pid()
                ),
                MemoryAlertSeverity::Critical,
                MitreTechnique {
                    id: "T1055".to_string(),
                    name: "Process Injection".to_string(),
                },
            ),
            InjectionTechniqueHint::Unknown => (
                "Suspicious Remote Thread / Injection Activity".to_string(),
                format!(
                    "Process {} (PID {}) performed suspicious actions towards {} (PID {}).",
                    ev.source_image(),
                    ev.source_pid(),
                    ev.target_image(),
                    ev.target_pid()
                ),
                MemoryAlertSeverity::High,
                MitreTechnique {
                    id: "T1055".to_string(),
                    name: "Process Injection".to_string(),
                },
            ),
        };

        MemoryAlert {
            severity,
            title,
            description: desc,
            mitre_techniques: vec![mitre],
            source_pid: ev.source_pid(),
            source_image: ev.source_image().to_string(),
            target_pid: Some(ev.target_pid()),
            target_image: Some(ev.target_image().to_string()),
            address: None,
            size: None,
            old_protection: None,
            new_protection: None,
            timestamp: ev.timestamp(),
        }
    }

    /// Analyze a memory-protection-change event (e.g. VirtualProtect).
    pub fn analyze_mem_prot<E: MemProtEventView>(&self, ev: &E) -> Option<MemoryAlert> {
        let old_exec = Self::is_exec_protection(ev.old_protection());
        let new_exec = Self::is_exec_protection(ev.new_protection());

        // Only care about non-exec -> exec transitions
        if old_exec || !new_exec {
            return None;
        }

        let severity = if ev.size() >= 0x1000 {
            MemoryAlertSeverity::High
        } else {
            MemoryAlertSeverity::Medium
        };

        let title = "Suspicious Memory Protection Change (RW → RX)".to_string();
        let desc = format!(
            "Process {} (PID {}) changed memory at 0x{:X} (size 0x{:X}) to executable (old=0x{:X}, new=0x{:X}).",
            ev.process_image(),
            ev.pid(),
            ev.address(),
            ev.size(),
            ev.old_protection(),
            ev.new_protection(),
        );

        Some(MemoryAlert {
            severity,
            title,
            description: desc,
            mitre_techniques: vec![MitreTechnique {
                id: "T1055".to_string(),
                name: "Process Injection".to_string(),
            }],
            source_pid: ev.pid(),
            source_image: ev.process_image().to_string(),
            target_pid: None,
            target_image: None,
            address: Some(ev.address()),
            size: Some(ev.size()),
            old_protection: Some(ev.old_protection()),
            new_protection: Some(ev.new_protection()),
            timestamp: ev.timestamp(),
        })
    }

    /// Analyze LSASS access indicative of credential dumping.
    pub fn analyze_lsass_access<E: LsassAccessEventView>(&self, ev: &E) -> Option<MemoryAlert> {
        // Typical credential dumping needs PROCESS_VM_READ and/or PROCESS_QUERY_INFORMATION.
        const PROCESS_VM_READ: u32 = 0x0010;
        const PROCESS_QUERY_INFORMATION: u32 = 0x0400;

        let mask = ev.access_mask();
        let wants_vm_read = (mask & PROCESS_VM_READ) != 0;
        let wants_query = (mask & PROCESS_QUERY_INFORMATION) != 0;

        if !wants_vm_read && !wants_query {
            return None;
        }

        let title = "Potential Credential Dumping - LSASS Access".to_string();
        let desc = format!(
            "Process {} (PID {}) requested access 0x{:X} to LSASS.",
            ev.source_image(),
            ev.source_pid(),
            mask
        );

        Some(MemoryAlert {
            severity: MemoryAlertSeverity::Critical,
            title,
            description: desc,
            mitre_techniques: vec![MitreTechnique {
                id: "T1003.001".to_string(), // LSASS Memory
                name: "OS Credential Dumping: LSASS Memory".to_string(),
            }],
            source_pid: ev.source_pid(),
            source_image: ev.source_image().to_string(),
            target_pid: None,
            target_image: Some("lsass.exe".to_string()),
            address: None,
            size: None,
            old_protection: None,
            new_protection: None,
            timestamp: ev.timestamp(),
        })
    }

    fn is_exec_protection(prot: u32) -> bool {
        // Windows PAGE_EXECUTE_*: 0x10, 0x20, 0x40, 0x80
        (prot & 0xF0) != 0
    }
}
